
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cscd488team@gmail.com
spring.mail.password=ugrpsjxzpedulxlx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=jdbc:postgresql://db.pfphgkldjqdhejefgwhf.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=*NewServer02

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true